name: CI/CD utilizando Vercel

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  job-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Obtendo nodejs 22
        uses: actions/setup-node@v3
        with: 
          node-version: 22.x

      - name: Instalando dependencias
        run: npm install

      - name: Testando aplicação
        run: npm run lint
        
      - name: Fazendo build
        run: npm run build
        
        env:
          CI: true

  job-CD:
    runs-on: ubuntu-latest
    needs: job-CI
    steps:
        - uses: actions/checkout@v3
    
        - name: Install Vercel CLI
          run: npm install --global vercel
    
        - name: Pull Vercel Environment Information
          run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    
        - name: Build Project Artifacts
          run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
    
        - name: Deploy Project Artifacts
          run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
